### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by hoseinsalehi** [ratesquant/ACQ#1]

**Comment by ratesquant** [comment]
Tutorial:
https://github.com/ratesquant/ACQ/blob/master/Distribution/Primer.Interpolation.pdf

Example Excel Spreadsheet:
https://github.com/ratesquant/ACQ/blob/master/Distribution/ACQ.Interpolation.xlsx

Code walk-through:
https://www.codeproject.com/Articles/1097174/Interpolation-in-Excel-using-Excel-DNA
